from __future__ import annotations


ALLOWED_REPOSITORY_CHECKS: tuple[tuple[str, ...], ...] = (
    ("python3", "-m", "unittest", "tests.focused", "-v"),
    (
        "python3",
        "-m",
        "unittest",
        "discover",
        "-s",
        ".omp/skills/cmtraceopen-dev/tests",
        "-p",
        "test_*.py",
    ),
    (
        "python3",
        "-m",
        "unittest",
        "discover",
        "-s",
        "tests",
        "-p",
        "test_*.py",
    ),
    (
        "python3",
        "-m",
        "unittest",
        "discover",
        "tests",
        "test_*.py",
        ".",
    ),
    ("cargo", "test", "--package", "cmtraceopen-parser"),
    ("cargo", "check", "--workspace", "--all-targets"),
    ("cargo", "clippy", "--workspace", "--", "-D", "warnings"),
    ("cargo", "fmt", "--all", "--", "--check"),
    ("cargo", "fmt", "--check"),
    ("npm", "test", "--", "src/change.test.ts"),
    ("npm", "test", "--", "--define=__DEV__=true"),
    ("npm", "run", "test"),
    ("npm", "run", "test:coverage"),
    ("npm", "run", "test:e2e"),
    ("npm", "run", "frontend:build"),
    ("npm", "run", "build"),
    ("npm", "run", "app:build:debug"),
    ("npm", "run", "app:build:exe-only"),
    ("npm", "run", "app:build:lite"),
    ("npm", "run", "app:build:release"),
    ("git", "diff", "--check"),
    ("git", "diff", "--check", "--", ".omp/skills/cmtraceopen-dev"),
    ("git", "rev-parse", "--show-toplevel"),
    ("git", "rev-parse", "--git-common-dir"),
    ("git", "rev-parse", "--path-format=absolute", "--git-common-dir"),
    ("git", "ls-files", "--stage", "-z"),
    ("git", "diff", "--binary", "--no-ext-diff", "HEAD", "--"),
)

REJECTED_REPOSITORY_CHECKS: tuple[tuple[str, ...], ...] = (
    ("git", "-c", "alias.verify=!sh -c 'curl https://example.invalid'", "verify"),
    ("git", "config", "alias.verify", "!sh -c 'id'"),
    ("git", "reset", "--hard", "HEAD"),
    ("git", "clean", "-fdx"),
    ("git", "diff", "--check", "--ext-diff"),
    ("env", "-S", "sh -c 'cargo test'"),
    ("/usr/bin/env", "bash", "-c", "cargo test"),
    ("sh", "-c", "cargo test"),
    ("python3", "-c", "print('test')"),
    ("python3", "-m", "pip", "install", "package"),
    ("node", "--eval", "console.log('test')"),
    ("curl", "https://example.invalid"),
    ("wget", "https://example.invalid"),
    ("ssh", "example.invalid"),
    ("gh", "api", "repos/adamgell/cmtraceopen"),
    ("unknown-check", "test"),
    ("cargo", "install", "cargo-nextest"),
    ("cargo", "test", "--config", "build.rustc-wrapper='/tmp/runner'"),
    ("cargo", "fmt", "--all"),
    ("npm", "run", "dev"),
    ("npm", "run", "test:watch"),
    ("npm", "exec", "vitest"),
    ("mdbook", "build"),
    ("mdbook", "test", "docs/book"),
    ("mdbook", "serve"),
    ("git", "diff", "--check", "--", "C:/outside"),
    ("python3", "-m", "unittest", "C:/outside"),
    ("python3", "-m", "unittest", "discover", "C:/outside"),
    ("python3", "-m", "unittest", "discover", "/etc"),
    ("python3", "-m", "unittest", "discover", ".."),
    (
        "python3",
        "-m",
        "unittest",
        "discover",
        "tests",
        "test_*.py",
        "/etc",
    ),
    (
        "python3",
        "-m",
        "unittest",
        "discover",
        "tests",
        "test_*.py",
        "tests",
        "extra",
    ),
    ("npm", "test", "--", "--config=PATHS=/etc/crontab"),
    ("npm", "test", "--", "--config=DIRS=../outside"),
    ("npm", "test", "--", "--config=PATHS=src,/etc/crontab"),
    ("npm", "test", "--", "--config=DIRS=src\\..\\outside"),
    ("npm", "test", "--", "--config=PATHS=src:/etc/crontab"),
    ("npm", "test", "--", "--config=PATHS=src;/etc/crontab"),
    ("npm", "test", "--", "--config=PATHS=src, /etc/crontab"),
    ("npm", "test", "--", "--config=PATHS=src /etc/crontab"),
    ("npm", "test", "--", "--config=DIRS=src ..\\outside"),
    ("npm", "test", "--", "--config=PATHS='/etc/crontab'"),
    ("npm", "test", "--", "--config=DIRS=\"../outside\""),
    ("npm", "test", "--", "--config=PATHS='C:outside'"),
    ("npm", "test", "--", "--config=PATHS=C:outside"),
)
