/**
 * Event Logs screenshot captures (`npm run screenshots -- -g event-logs`).
 *
 * Kept apart from capture.spec.ts so the two files can change independently. The `outPath` and
 * `dismissSplash` helpers below are copies of the ones there; consolidate them once both files
 * settle.
 *
 * Data path
 * ---------
 * The workspace is driven through its real load path: `useEvtxStore.parseFiles(paths)` calls
 * `evtx_parse_files`, then the analysis pump calls the `evtx_*_analysis_*` commands. All of them
 * are answered by `window.__e2e_ipc_overrides__`:
 *
 * - `evtx_parse_files` is built by `buildParseResult()` (it needs real .evtx files to come from
 *   the backend), following `parse_evtx_manifest`.
 * - the analysis-session and diagnosis commands REPLAY replies captured from the real engine
 *   (`event-log-engine-replies.json`, regenerated by `capture-event-log-replies.mjs`). Each
 *   override first checks that the UI's request matches what the engine was asked during the
 *   capture, and throws otherwise, so a stale capture fails loudly instead of replaying.
 *
 * The 127.0.0.1:1422 IPC bridge is blocked, so a running `npm run app:dev` cannot leak live host
 * replies into a capture: a command with no override gets the shim's static defaults.
 *
 * These captures are the baseline of the CURRENT Event Logs UI.
 */
import path from "node:path";
import { fileURLToPath } from "node:url";
import { test, expect } from "../fixtures";
import {
  buildParseResult,
  EVENT_LOG_FIXTURE_PATHS,
  loadEngineReplies,
} from "../fixtures/event-log-data";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.resolve(HERE, "..", "..", "screenshots");
const outPath = (name: string) => path.join(OUT_DIR, name);

async function dismissSplash(
  page: import("@playwright/test").Page,
): Promise<void> {
  await page.waitForSelector("#splash", { state: "detached", timeout: 15_000 });
}

// Timestamps render in local time; pin the zone and locale so the PNGs do not depend on the host.
test.use({ timezoneId: "UTC", locale: "en-US" });

test.describe("event-logs screenshots", () => {
  let timelineGridName: string;

  test.beforeEach(async ({ page }) => {
    const parseResult = buildParseResult();
    const replies = loadEngineReplies();
    timelineGridName = `Event log timeline - ${parseResult.records.length} records`;

    // Same guard as e2e/fixtures/index.ts: nothing here may talk to a running backend.
    await page.route("http://127.0.0.1:1422/**", (route) =>
      route.abort("connectionrefused"),
    );

    await page.addInitScript(
      ({ parseResult, replies, paths }) => {
        const overrides = window.__e2e_ipc_overrides__;
        const same = (a: unknown, b: unknown): boolean =>
          JSON.stringify(a) === JSON.stringify(b);
        const stale = (command: string, detail: string): Error =>
          new Error(
            `[event-logs fixture] ${command}: ${detail}. ` +
              "Regenerate with `node e2e/fixtures/capture-event-log-replies.mjs`.",
          );
        const requireSession = (command: string, args: { sessionId: string }) => {
          if (args.sessionId !== replies.sessionId) {
            throw stale(command, `unexpected session id ${args.sessionId}`);
          }
        };

        let appendCalls = 0;
        overrides["evtx_parse_files"] = (args: { paths: string[] }) => {
          if (!same(args.paths, paths)) {
            throw stale("evtx_parse_files", "requested paths differ from the fixture's");
          }
          return parseResult;
        };
        overrides["evtx_create_analysis_session"] = () => {
          appendCalls = 0;
          return replies.create;
        };
        overrides["evtx_append_analysis_chunk"] = (args: {
          sessionId: string;
          records: unknown[];
          entries: unknown[];
        }) => {
          requireSession("evtx_append_analysis_chunk", args);
          const expected = replies.appendChunkRecordCounts[appendCalls];
          if (args.records.length !== expected || args.entries.length !== 0) {
            throw stale(
              "evtx_append_analysis_chunk",
              `chunk ${appendCalls} carried ${args.records.length} records and ` +
                `${args.entries.length} entries, the capture saw ${expected} and 0`,
            );
          }
          return replies.append[appendCalls++];
        };
        overrides["evtx_finalize_analysis_session"] = (args: { sessionId: string }) => {
          requireSession("evtx_finalize_analysis_session", args);
          return replies.finalize;
        };
        overrides["evtx_query_analysis_timeline"] = (args: {
          sessionId: string;
          offset: number;
          limit: number;
        }) => {
          requireSession("evtx_query_analysis_timeline", args);
          const captured = replies.timelinePages.find(
            (entry) => entry.offset === args.offset && entry.limit === args.limit,
          );
          if (!captured) {
            throw stale(
              "evtx_query_analysis_timeline",
              `no captured page for offset ${args.offset}, limit ${args.limit}`,
            );
          }
          return captured.page;
        };
        overrides["evtx_diagnose_analysis_session"] = (args: {
          sessionId: string;
          coverageGaps: unknown[];
        }) => {
          requireSession("evtx_diagnose_analysis_session", args);
          if (!same(args.coverageGaps, replies.diagnoseCoverageGaps)) {
            throw stale(
              "evtx_diagnose_analysis_session",
              "coverage gaps differ from the ones the engine was given",
            );
          }
          return replies.diagnosis;
        };
        overrides["evtx_close_analysis_session"] = () => null;
        // No saved markers for the fictional files.
        overrides["load_markers"] = () => null;
      },
      { parseResult, replies, paths: EVENT_LOG_FIXTURE_PATHS },
    );

    await page.goto("/");
    await dismissSplash(page);

    await page.evaluate(async (paths) => {
      const { useUiStore } = await import("/src/stores/ui-store.ts");
      const { useEvtxStore } = await import(
        "/src/workspaces/event-log/evtx-store.ts"
      );
      useUiStore.getState().setActiveWorkspace("event-log");
      await useEvtxStore.getState().parseFiles(paths);
    }, EVENT_LOG_FIXTURE_PATHS);

    // The grid, the diagnosis card and a loaded unified-timeline row all depend on the full
    // parse and analysis round trip, so together they mean the workspace has settled.
    await expect(page.getByRole("grid", { name: timelineGridName })).toBeVisible({
      timeout: 15_000,
    });
    await expect(page.getByLabel("Operational diagnosis")).toBeVisible({
      timeout: 15_000,
    });
    await expect(page.getByText("Loading timeline row")).toHaveCount(0);

    // Newest first, through the filter bar's own sort control, so the Warning, Error and
    // Critical rows are on screen instead of the early-morning run of Information rows.
    await page
      .getByRole("button", { name: "Change sort direction to descending" })
      .click();
    await expect(
      page.getByRole("button", { name: "Change sort direction to ascending" }),
    ).toBeVisible();
  });

  test("event-logs table", async ({ page }) => {
    await expect(page.getByRole("region", { name: "Event log details" })).toHaveCount(0);
    await page.screenshot({
      path: outPath("event-logs-table.png"),
      animations: "disabled",
    });
  });

  test("event-logs selected record", async ({ page }) => {
    const grid = page.getByRole("grid", { name: timelineGridName });
    // Newest first, the first Error record (MsiInstaller 11708) is the 39th row, below the fold of
    // a virtualized list, so scroll it into the rendered window before clicking.
    await grid.evaluate((el) => {
      el.scrollTop = 36 * 36;
    });
    const row = grid
      .getByRole("row")
      .filter({ hasText: "Installation failed." })
      .first();
    await row.click();
    await expect(
      page.getByRole("region", { name: "Event log details" }),
    ).toContainText("Installation failed.");
    await page.screenshot({
      path: outPath("event-logs-selected.png"),
      animations: "disabled",
    });
  });
});
